# Generated by Django 4.1.7 on 2023-03-14 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('movie', models.CharField(max_length=100)),
                ('evaluation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('impression', models.CharField(max_length=1000)),
            ],
        ),
    ]
