# Generated by Django 4.1.7 on 2023-03-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='id',
        ),
    ]
