# Generated by Django 4.1.7 on 2023-03-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_uuid_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='impression',
            field=models.CharField(max_length=2000),
        ),
    ]
